[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-fund --no-audit"
  NETLIFY_USE_PNPM = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200